name: Update Proxy Configs
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-configs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: main-repo

    - name: Checkout free-server repository
      uses: actions/checkout@v3
      with:
        repository: m3hdiclub/free-server
        token: ${{ secrets.PAT_TOKEN }}  # You'll need to create this secret
        path: free-server
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        cd main-repo
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create directories
      run: |
        cd main-repo
        mkdir -p assets
        mkdir -p configs
    
    - name: Run config fetcher
      run: |
        cd main-repo
        python src/fetch_configs.py
      continue-on-error: true
    
    - name: Generate charts and reports
      run: |
        cd main-repo
        python src/generate_charts.py
    
    - name: Update README timestamps
      run: |
        cd main-repo
        timestamp=$(date +%s)
        sed -i "s/channel_stats_chart\.svg?v=[0-9]*/channel_stats_chart.svg?v=$timestamp/" README.md
        sed -i "s/performance_report\.html?v=[0-9]*/performance_report.html?v=$timestamp/" README.md
    
    - name: Setup Git for main repo
      run: |
        cd main-repo
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Commit and push changes to main repo
      run: |
        cd main-repo
        git add configs/channel_stats.json
        git add assets/channel_stats_chart.svg
        git add assets/performance_report.html
        git add README.md
        git commit -m "Update stats and reports" || echo "No changes to commit"
        git push

    - name: Setup Git for free-server repo
      run: |
        cd free-server
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Commit and push changes to free-server repo
      run: |
        cd free-server
        git add subscription_1
        git commit -m "Update proxy configurations" || echo "No changes to commit"
        git push
